# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG NODE_VERSION=alpine

################################################################################
# Use node image for base image for all stages.
FROM node:${NODE_VERSION} AS dev

# Set working directory for all build stages.
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

# Install all dependencies, including dev dependencies.
RUN --mount=type=cache,target=/root/.npm \
    npm install

# Copy the rest of the source files into the image.
COPY . .

EXPOSE 8000

CMD [ "npm" , "run", "dev" ]

